/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopapp;






import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author donwhelan1
 */
public class ShopGUI extends javax.swing.JFrame {

    private ArrayList<Shop> shops;
    public ShopGUI() {
        initComponents();
        shops = new ArrayList<Shop>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtProd = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ShopApp");

        jLabel1.setText("PRODUCT");

        jLabel2.setText("ID");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Display");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtProd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addComponent(jButton8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(20, 20, 20))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnSave)
                .addGap(55, 55, 55)
                .addComponent(btnLoad)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton8))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnLoad))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 322));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        String tempProd, tempIdString;
        int tempId;
        tempProd = txtProd.getText();
        tempIdString = txtId.getText();
        tempId = Integer.parseInt(tempIdString);
        Shop tempShop = new Shop();
        tempShop.setProd(tempProd);
        tempShop.setId(tempId);
        shops.add(tempShop);
        JOptionPane.showMessageDialog(rootPane,"Added");
        txtProd.setText("");
        txtId.setText("");
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(rootPane,"Format for submission must be" + "\n" + "Product must be a String" + "\n" + "ID must be a int");
        txtProd.setText("");
        txtId.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        for(int i=0;i<shops.size(); i++){
            Shop tempShop = shops.get(i);
            String tempInfo = tempShop.getInfo();
            JOptionPane.showMessageDialog(rootPane,tempInfo);
        }
        txtProd.setText("");
        txtId.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       String prodToFind;
       prodToFind = txtProd.getText();
       for(int i=0;i<shops.size();i++){
           Shop tempShop = shops.get(i);
           String tempProd = tempShop.getProd();
           if(prodToFind.equals(tempProd)){
               String tempInfo = tempShop.getInfo();
               JOptionPane.showMessageDialog(rootPane,"Found" + tempInfo);
           }
       }
       txtProd.setText("");
       txtId.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String idToFindString;
        int idToFind;
        idToFindString = txtId.getText();
        idToFind = Integer.parseInt(idToFindString);
        for(int i=0; i<shops.size(); i++){
            Shop tempShop = shops.get(i);
            int tempId = tempShop.getId();
            if(idToFind == tempId){
                String tempInfo = tempShop.getInfo();
                JOptionPane.showMessageDialog(rootPane,"found" + tempInfo);
            }
            
        }
        txtProd.setText("");
        txtId.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String prodToFind;
        prodToFind = txtProd.getText();
        for(int i=0; i<shops.size();i++){
            Shop tempShop = shops.get(i);
            String tempProd = tempShop.getProd();
            if(prodToFind.equals(tempProd)){
            shops.remove(i);
            String tempInfo = tempShop.getInfo();
            JOptionPane.showMessageDialog(rootPane,"deleted" + tempInfo);
            }
        }
        txtProd.setText("");
        txtId.setText("");
    
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try{
            FileOutputStream fileOut = new FileOutputStream("file.file");
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            
            for(int i=0;i<shops.size();i++){
                Shop tempShop = shops.get(i);
                out.writeObject(tempShop);
            }
            out.close();
            fileOut.close();
        }
        catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(rootPane,"ERROR!" + ex);
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(rootPane,"ERROR!" + ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed

        try{
            FileInputStream fileIn = new FileInputStream("file.file");
            ObjectInputStream in = new ObjectInputStream(fileIn);
            
            try{
                shops.clear();
                Shop tempShop = (Shop)in.readObject();
                shops.add(tempShop);
            }
            catch(EOFException ex){
                in.close();
                fileIn.close();
            }
        }
        catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(rootPane,"ERROR!" + ex);
        }
        catch(IOException ex){
            JOptionPane.showMessageDialog(rootPane,"ERROR!" + ex);
        }
        
    }//GEN-LAST:event_btnLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtProd;
    // End of variables declaration//GEN-END:variables
}


/*SAVE
        try{
            FileOutputStream fileOut = new FileOutputStream("shop3.bin");
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            
            for(int i=0;i<shops.size(); i++){
                Shop tempShop = shops.get(i);
                out.writeObject(tempShop);
            }
            out.close();
            fileOut.close();
                
        }
        catch (FileNotFoundException ex){
            JOptionPane.showConfirmDialog(rootPane, "Error!" + ex);
        }
        catch(IOException ex){
             JOptionPane.showConfirmDialog(rootPane, "Error!" + ex);
        }*/

/*LOAD
try{
            FileInputStream fileIn = new FileInputStream("shop3.bin");
            ObjectInputStream in = new ObjectInputStream(fileIn);
            
            try{
                shops.clear();
                while(true){
                    Shop tempShop = (Shop)in.readObject();
                    shops.add(tempShop);
                } 
            }
            catch(EOFException ex) {
                        in.close();
                        fileIn.close();
            } 
              
        }
        catch(IOException ex){
            JOptionPane.showConfirmDialog(rootPane, "Error!" + ex);
        }
        catch (ClassNotFoundException ex) {
               JOptionPane.showConfirmDialog(rootPane, "Error!" + ex); 
            }*/
